// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCmFgRDJhdSWMBzehtWdGfv9AHmHgFyEE',
    appId: '1:893286377789:web:5f6f52ca917736f5ad3d54',
    messagingSenderId: '893286377789',
    projectId: 'janyukti-1cbba',
    authDomain: 'janyukti-1cbba.firebaseapp.com',
    storageBucket: 'janyukti-1cbba.firebasestorage.app',
    measurementId: 'G-C2880ZW1DE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_pnV3t4Mu9A_Athr0M6LZMc7SenvPIDY',
    appId: '1:893286377789:android:ae75fe87ca4f9ac6ad3d54',
    messagingSenderId: '893286377789',
    projectId: 'janyukti-1cbba',
    storageBucket: 'janyukti-1cbba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC46GYrUXpqq57Nw93M_VK2rBAD3byy-I',
    appId: '1:893286377789:ios:275a842c598960dcad3d54',
    messagingSenderId: '893286377789',
    projectId: 'janyukti-1cbba',
    storageBucket: 'janyukti-1cbba.firebasestorage.app',
    iosBundleId: 'com.aditya.janyukti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC46GYrUXpqq57Nw93M_VK2rBAD3byy-I',
    appId: '1:893286377789:ios:275a842c598960dcad3d54',
    messagingSenderId: '893286377789',
    projectId: 'janyukti-1cbba',
    storageBucket: 'janyukti-1cbba.firebasestorage.app',
    iosBundleId: 'com.aditya.janyukti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCmFgRDJhdSWMBzehtWdGfv9AHmHgFyEE',
    appId: '1:893286377789:web:da4f634a7bd158e1ad3d54',
    messagingSenderId: '893286377789',
    projectId: 'janyukti-1cbba',
    authDomain: 'janyukti-1cbba.firebaseapp.com',
    storageBucket: 'janyukti-1cbba.firebasestorage.app',
    measurementId: 'G-BZDPTT1191',
  );
}
